import React from 'react'

const Education = () => {
  return (
     <div className='flex justify-center'>
            <span className=''>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus luctus aliquet pretium. Duis hendrerit ultrices neque, vitae egestas turpis malesuada ut. Nullam sed viverra odio. Donec id sagittis metus. Donec pellentesque quam sit amet erat molestie convallis. Phasellus ac lorem consectetur, suscipit nunc quis, scelerisque nibh. Phasellus dolor lectus, porttitor vel egestas et, pretium id lorem. Nunc mi ipsum, suscipit vitae est vel, semper mattis nibh.

Donec sed faucibus libero. Aenean rhoncus hendrerit nisi, a porttitor augue faucibus eu. Vestibulum efficitur lacus ut velit iaculis, in facilisis augue imperdiet. Vivamus ultrices commodo elit, vitae suscipit nunc hendrerit sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras vestibulum nulla lorem, non laoreet augue congue quis. Duis odio dolor, tempor ut eros non, consequat commodo turpis. Aliquam et convallis tortor. Sed luctus luctus massa, vel aliquet turpis feugiat id. Maecenas nulla diam, aliquet sed risus ut, vehicula congue lacus. Sed at eleifend turpis. Integer a varius enim. Praesent congue, erat sed ultricies fermentum, magna elit bibendum odio, ac sollicitudin velit dolor a leo. Suspendisse finibus arcu tortor, consectetur tristique tellus posuere rutrum. Quisque pulvinar accumsan pellentesque. Cras elementum luctus sodales.

Mauris odio arcu, fringilla quis libero vel, pretium dapibus risus. Aenean id euismod nisi, vitae sodales mi. Nulla hendrerit laoreet nunc, vitae maximus neque pellentesque eget. Nullam cursus nisl quis tellus iaculis, at viverra dolor interdum. Integer quis enim eleifend, commodo mauris vel, mattis enim. Ut sit amet fermentum velit, id scelerisque nibh. Maecenas rhoncus imperdiet ante. Donec sagittis sem orci, in consectetur nunc interdum ut. Quisque consequat erat at dapibus viverra. Quisque sed turpis tincidunt, pellentesque nulla sit amet, congue ex. Vestibulum commodo velit at iaculis tempus. Curabitur lacinia lorem magna, ut aliquet libero commodo in.

Vestibulum in dignissim arcu. Integer laoreet felis ac nulla congue egestas. Mauris eget justo pretium, ultricies diam eget, tincidunt nisi. Aliquam blandit dolor eros, eu vehicula nulla congue eu. Nunc tristique eleifend lorem non aliquam. Vivamus vitae lectus pretium orci vulputate semper nec at lorem. Maecenas non viverra augue. Pellentesque ipsum massa, vestibulum et elementum eu, venenatis eget diam. Vivamus eu velit rutrum justo tristique tincidunt sit amet vel dui. Etiam nec orci id ipsum malesuada rutrum ac vitae metus. Maecenas a eleifend tortor, ut elementum orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris et suscipit diam.

Suspendisse et nibh id lectus sodales molestie et ut nibh. Ut vitae libero et ante ultricies malesuada. Aliquam erat volutpat. Nulla mollis, tortor id commodo ullamcorper, tellus purus dictum neque, sit amet sagittis erat mi ut est. Praesent efficitur ligula sem, eget suscipit turpis feugiat vitae. Vestibulum eleifend enim id nunc ullamcorper, a interdum lectus sagittis. Cras congue, metus at feugiat tincidunt, risus ipsum lacinia tellus, in ornare dui lacus quis nulla. Aenean condimentum odio eu odio molestie imperdiet. Suspendisse potenti. Suspendisse quis consequat sem. Maecenas id eros sit amet sapien placerat laoreet.

Proin ac dolor porttitor, imperdiet risus eget, dictum mauris. Aenean ante est, mollis at sagittis ut, pharetra a tellus. Ut auctor est quis nisl auctor, semper volutpat nunc suscipit. Etiam vestibulum nibh a tristique vulputate. Ut et pharetra erat. In euismod porttitor tempor. Morbi vel enim velit. Suspendisse iaculis fringilla libero, et luctus orci vestibulum in. Suspendisse tincidunt tortor et iaculis fermentum.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec eleifend nibh. Suspendisse mollis sem a lacus dapibus, vitae mattis libero mollis. Mauris id aliquam erat. Etiam venenatis dui quis felis gravida, sed dapibus arcu ultrices. Vestibulum ut neque ligula. Nulla non est augue. Phasellus dictum erat at velit tincidunt, sed euismod leo sollicitudin. Aenean fermentum, lorem id efficitur auctor, ante eros vulputate dolor, ac viverra mi elit sed erat. Vivamus eget dignissim nibh, eget pretium dolor.

Curabitur arcu tellus, lobortis ut fringilla eu, aliquet quis ligula. Donec hendrerit nulla nec risus commodo mattis. Duis eu placerat lorem, at gravida ligula. Nulla viverra sapien nec pharetra tincidunt. Phasellus feugiat risus vel eleifend imperdiet. Proin sit amet arcu turpis. Donec risus ante, pulvinar venenatis massa a, tempus malesuada dui. Curabitur laoreet erat nec placerat viverra. Phasellus tempor nibh odio, ac ullamcorper ipsum malesuada eget. Praesent rutrum efficitur magna eget pulvinar. Sed non metus egestas, gravida odio eget, dapibus ipsum. Aliquam dictum ornare dictum.

Curabitur dignissim ante non scelerisque accumsan. Quisque aliquam eu orci ut vestibulum. Donec rhoncus, mauris at pretium viverra, lacus dui porttitor nibh, in dignissim libero ipsum at turpis. Etiam ut augue eu nisl tempus cursus a at libero. Ut ornare auctor purus tincidunt ultrices. Morbi tristique, urna et aliquet tempus, nulla sapien gravida augue, non pretium leo ipsum quis libero. Curabitur tincidunt vitae tortor non ullamcorper. Etiam at eros mauris. Duis tempus massa dolor, a accumsan arcu tincidunt non. Nunc iaculis hendrerit arcu id tempus. Sed pharetra imperdiet arcu et mattis. Quisque nec feugiat enim. Vivamus auctor, augue id gravida consequat, felis nibh tincidunt purus, at blandit dolor dolor quis tortor. Quisque placerat erat non hendrerit congue. Duis ac purus nec sem porta molestie. Proin magna mauris, fringilla finibus laoreet nec, sagittis iaculis felis.

Phasellus id ante ut odio iaculis rutrum. Sed id mattis urna, id semper ex. Nullam semper turpis facilisis, tristique augue nec, dictum metus. Mauris nec sollicitudin purus. Phasellus luctus leo et euismod euismod. Proin iaculis nibh quis ex pulvinar, a suscipit mauris pharetra. In non nibh in risus bibendum rutrum. Duis id euismod lorem. Aliquam sodales malesuada porttitor. Nunc condimentum rutrum imperdiet. Curabitur lobortis ex id aliquet pretium. Curabitur auctor metus mi, vitae finibus elit dignissim sed. Donec sem augue, scelerisque sit amet lorem non, pellentesque auctor turpis. Praesent tincidunt eu lectus eu iaculis.

Aenean malesuada mi id consectetur porta. Ut semper tincidunt tellus, non cursus magna lacinia a. Nullam lacus mi, blandit vel ullamcorper eu, dignissim id nibh. Donec posuere nibh id urna eleifend, sit amet molestie elit consectetur. Vestibulum id sagittis orci, convallis vestibulum leo. Proin hendrerit risus eu feugiat vehicula. Duis nec lectus mi. Nulla facilisi. Curabitur mollis augue nec eros fermentum faucibus. Sed viverra nisl eget laoreet eleifend. Nunc in mauris id magna blandit convallis nec eu ex.

Vivamus sit amet mi enim. Vestibulum nec placerat mauris. Phasellus lobortis maximus dolor eget suscipit. Sed ultricies dui in libero bibendum consectetur. Phasellus molestie, nisl viverra scelerisque rhoncus, massa nulla tristique ipsum, id porttitor eros erat sit amet lacus. Aliquam euismod aliquet ante sed vehicula. Curabitur sagittis luctus diam. Nam eget diam tellus. Nam at consectetur sem. Duis nec dictum mi. Praesent mattis mauris nec lorem sollicitudin finibus. Vivamus quis vestibulum sapien. Nunc at nunc dapibus, pretium turpis quis, suscipit velit.

Donec ipsum lectus, rhoncus a lectus blandit, maximus vulputate enim. Phasellus sodales massa orci, facilisis convallis nunc tempor ut. Pellentesque viverra non tellus id mollis. Duis a tellus iaculis, posuere eros sit amet, interdum massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eget varius mauris. Maecenas vel ipsum dignissim, pharetra elit vitae, molestie mauris. Donec sed lectus quam. Nullam accumsan suscipit purus vel accumsan. Pellentesque ac elit sed sapien malesuada pellentesque eu a quam. Nullam sed efficitur nunc, et imperdiet ex.

Sed vel finibus dui. Praesent sed eleifend ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent pretium eu enim vel tristique. Pellentesque mattis dapibus lorem. Aliquam a turpis luctus, suscipit mauris eu, vulputate urna. Praesent libero metus, iaculis ut mi imperdiet, accumsan ultrices ante. Nullam at libero semper, blandit nunc non, consectetur ex. Donec vitae leo pretium tortor laoreet commodo. Morbi placerat, dolor et scelerisque egestas, eros est gravida purus, at mattis risus dui et nulla. Praesent ultrices eros ac nulla mollis auctor. Praesent consequat id tellus eu mattis. Proin faucibus finibus tincidunt.

Aenean quis risus et metus tempus aliquet. Mauris nec turpis eu quam scelerisque maximus eget eu lacus. Suspendisse porta urna nec aliquam tempor. Vestibulum nec lacus bibendum urna cursus bibendum id sit amet libero. Donec eu tortor tincidunt, efficitur diam pellentesque, tincidunt felis. Aliquam non velit vitae arcu mattis lobortis at sit amet purus. Vestibulum interdum lorem nec facilisis lacinia. Ut velit ipsum, dignissim id vulputate at, pharetra at mauris.

Vivamus risus tortor, mattis a nunc a, ultricies efficitur metus. Vivamus vitae nulla sem. Curabitur pharetra, libero ut imperdiet pretium, mauris lacus blandit quam, eget mattis ligula lorem in massa. Ut nulla dui, congue sed orci at, commodo scelerisque tellus. Phasellus sed finibus urna. Morbi vehicula felis nec rhoncus placerat. Etiam quis orci nec ligula malesuada elementum mattis et odio. Donec pulvinar turpis vel nulla accumsan, a mollis odio feugiat. Cras quis metus in magna lacinia hendrerit. In id nulla pellentesque, tincidunt odio ut, maximus odio. Pellentesque viverra dapibus neque, eget facilisis nunc ullamcorper et. Phasellus fermentum eget mauris ac dapibus. Vestibulum tincidunt vitae tellus dapibus blandit.

In imperdiet auctor venenatis. Mauris blandit mattis velit vitae sollicitudin. Duis non urna non risus ultricies accumsan eu sed massa. Vestibulum lacinia molestie urna. Praesent sodales ante in sapien vulputate, cursus mattis nulla sagittis. Etiam vel sapien ac elit cursus viverra nec eget arcu. Cras id gravida arcu. Sed semper commodo ex, id semper ipsum. Curabitur non augue mattis, dictum nulla vitae, imperdiet nisl.

Vivamus faucibus pharetra enim ac laoreet. Etiam non est a orci pellentesque ultrices in non nibh. Maecenas eget pellentesque nunc. Duis vulputate non erat sed interdum. Maecenas fringilla porttitor nibh sit amet molestie. Sed dictum at lacus quis malesuada. Integer ac dapibus purus. Phasellus quis pulvinar lorem, quis sagittis felis. Nam tincidunt tortor ut nisl lobortis commodo. Aliquam sit amet nisl lacinia, porttitor velit quis, eleifend tortor. Suspendisse odio turpis, luctus sed facilisis ac, blandit et lacus.

Integer cursus cursus est, sit amet volutpat orci tempus pretium. Sed eget purus commodo tellus porta tincidunt at sed risus. Aliquam erat volutpat. Mauris aliquam eleifend urna nec molestie. Fusce suscipit ligula nunc, non dapibus sem dictum ut. Maecenas congue ac quam dapibus dapibus. Fusce bibendum enim ac metus iaculis malesuada. Nunc pellentesque hendrerit magna, vitae accumsan dui mattis vel. Curabitur porta pellentesque suscipit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus feugiat ipsum a arcu egestas tempus. Cras vel tortor ut nisi vulputate suscipit. Donec sed vestibulum diam. Sed turpis mauris, suscipit non convallis ut, laoreet et massa.

Sed ac felis mollis, sagittis erat nec, vestibulum nibh. Aliquam at nisl sit amet mauris sagittis placerat non vitae magna. In non purus lacus. Donec lacus lectus, euismod et dignissim vitae, tincidunt et ex. Vivamus pretium molestie justo, vitae rhoncus lorem lobortis ac. Suspendisse iaculis felis sagittis lacus commodo, quis laoreet mi aliquam. Donec tristique elementum quam, sed aliquam augue semper fermentum. Donec fermentum leo fermentum justo faucibus, molestie fringilla elit placerat. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consectetur dictum nisi, vitae auctor turpis tempor in.
            </span>
    </div>
  )
}

export default Education
